### ISSUE TITLE
Add some basic docs

### ISSUE THREAD

**Issue by ivanvaccari** [bkeevil/arduino-mqtt#2]
Hi. I'm valuating this library for my home project but while it's quite easy to setup, i had some inetersting time finding out why, without any change, the compilation process output a code who would not fit into an arduino uno.

The solution was to reduce MQTT_MAX_DATA_LEN, MQTT_MAX_TOPIC_LEN and MQTT_PACKET_QUEUE_SIZE in order to create smaller buffers.

I suggest to you to add just some lines in the readme file just to warn the user about this.

**Comment by bkeevil** [comment]
Fixed in f345d40
