### ISSUE TITLE
Compilation fail: misspell of 'QoS'

### ISSUE THREAD

**Issue by ivanvaccari** [bkeevil/arduino-mqtt#3]
https://github.com/bkeevil/arduino-mqtt/blob/150b77f3acbef321fc7a366533c3bcc740d12ca2/mqtt.h#L362

This code line cause the compilation to fail with the official arduino sdk.
The right field for the object willMessage is 'qos' and not 'QoS' ( note the lower/uppercase)

**Comment by bkeevil** [comment]
Fixed with 09e77ea
